name = str(input("Enter your name:"))
age = int(input("Enter your age:"))
rollnumber = int(input("Enter your rollnumber:"))
phonenumber = int(input("Enter your phonenumber:"))
print("This is your name",name)
print("This is your age", age)
print("This is your rollnumber", rollnumber)
print("This is your phonenumber", phonenumber)
